# Corpus query, download, and review

**Date:** 2026-07-03 (system date)

This notebook helps you:

1. Search Europe PMC for scientific papers
2. Download fulltext XML where available
3. Build a scored review table for human curation
4. Refine your query and compare results

Documentation:
- [build_review_table.md](https://github.com/semanticClimate/semantic_corpus/blob/main/docs/build_review_table.md)
- [aqi_india_corpus_workflow.md](https://github.com/semanticClimate/semantic_corpus/blob/main/docs/aqi_india_corpus_workflow.md)
- [colab_corpus_review_notebook.md](https://github.com/semanticClimate/semantic_corpus/blob/main/docs/colab_corpus_review_notebook.md)

## 1. Install dependencies

In [ ]:
!pip install -q git+https://github.com/semanticClimate/semantic_corpus.git
!pip install -q pandas ipywidgets

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 7.2 MB/s eta 0:00:00
  Building wheel for semantic_corpus (pyproject.toml) ... done
  Building wheel for bagit (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 46.4 MB/s eta 0:00:00

## 2. Parameters

Edit these values before each run. Set `REVISION_OF` when refining a previous query.

In [ ]:
from pathlib import Path

QUERY_NAME = "aqi_india_pilot"
QUERY_STRING = (
    '("ambient air pollution" OR AQI) '
    'AND (India) '
    'AND (PM2.5 OR PM10) '
    'AND (climate OR environment OR seasonal OR meteorology)'
)
LIMIT = 50
FORMATS = ["xml"]
REPOSITORY = "europe_pmc"
NOTES = ""
REVISION_OF = None  # e.g. "aqi_india_pilot" when refining a prior run

OUTPUT_DIR = Path("/content/queries", QUERY_NAME)
OUTPUT_DIR

PosixPath('/content/queries/aqi_india_pilot')

## 3. Run query, download, and build review table

In [ ]:
from semantic_corpus.corpus_review.workflow import run_query_and_build_review_table

result = run_query_and_build_review_table(
    query_name=QUERY_NAME,
    query_string=QUERY_STRING,
    output_dir=OUTPUT_DIR,
    repository=REPOSITORY,
    limit=LIMIT,
    formats=FORMATS,
    notes=NOTES,
    revision_of=REVISION_OF,
)

print(result["summary"])
print(f"Rows: {result['row_count']} (score >= 5: {result['high_score_count']}, with XML: {result['xml_count']})")
print("Review files:")
for fmt, path in result["review_paths"].items():
    print(f"  {fmt}: {path}")

Query 'aqi_india_pilot': 50 results, 47 downloaded -> /content/queries/aqi_india_pilot
Rows: 50 (score >= 5: 18, with XML: 47)
Review files:
  json: /content/queries/aqi_india_pilot/review/review_table.json
  csv: /content/queries/aqi_india_pilot/review/review_table.csv
  markdown: /content/queries/aqi_india_pilot/review/review_table.md

## 4. Browse results (immediate reaction)

Inspect top candidates. Score ranks papers for review; it does **not** auto-include them.

In [ ]:
from semantic_corpus.corpus_review.workflow import review_rows_to_dataframe

df = review_rows_to_dataframe(result["rows"])

display_cols = [
    "score",
    "title",
    "pmcid",
    "has_xml",
    "location_terms",
    "pollutant_terms",
    "review_status",
]
display(df[display_cols].head(15))

print("\nHigh-score papers with XML:")
high_xml = df[(df["score"] >= 5) & (df["has_xml"] == True)]
print(f"  {len(high_xml)} of {len(df)} rows")
display(high_xml[display_cols])

,score,title,pmcid,has_xml,location_terms,pollutant_terms,review_status
0,9,Explainable forecasting of air quality index u...,PMC12329590,True,india,"aqi, air quality index",review
1,8,Assessment and forecasting of particulate matt...,PMC12098713,True,bangalore,"aqi, air quality index, particulate matter",review
2,8,Health and economic effects of air pollution i...,PMC12538240,True,india,"ambient air pollution, air pollution",review
3,8,Respiratory deposition of particulate matter i...,PMC12663435,True,"india, delhi","particulate matter, air pollution",review
4,8,Impact of Housing Conditions and Air Quality A...,PMC12815361,True,india,"pm2.5, particulate matter, air pollution",review
5,8,Real-time impacts of air pollution on the heal...,PMC13289869,True,"india, delhi","pm2.5, particulate matter, air pollution",review
6,7,Assessing Nexus between Human Health and Air P...,,False,"india, indian","aqi, air quality index, pm2.5, pm10, particula...",review
7,6,Ensemble stacking of machine learning models f...,PMC11883379,True,"india, hyderabad","aqi, air quality index, air pollution",review
8,6,Estimating health and economic burden of PM&lt...,PMC12287331,True,india,"particulate matter, air pollution",review
9,6,Efficient multi-station air quality prediction...,PMC12364328,True,delhi,"pm2.5, particulate matter",review
10,6,Effect of Ambient Air Pollutants on Acute chan...,PMC12572900,True,india,"aqi, air quality index, pm2.5, pm10, particula...",review
11,6,Alterations in neuroinflammatory and neurodege...,PMC12753801,True,"india, indian","ambient air pollution, air pollution, ozone",review
12,6,Role of wind in alteration of hilltop airborne...,PMC12838236,True,india,particulate matter,review
13,6,Role of medicines dispensation data in city-ba...,PMC12851262,True,"india, indian, pune","particulate matter, air pollution",review
14,6,A cross-sectional study on the respiratory hea...,PMC12995173,True,"india, tamil nadu","pm2.5, pm10",review

High-score papers with XML:
  17 of 50 rows

,score,title,pmcid,has_xml,location_terms,pollutant_terms,review_status
0,9,Explainable forecasting of air quality index u...,PMC12329590,True,india,"aqi, air quality index",review
1,8,Assessment and forecasting of particulate matt...,PMC12098713,True,bangalore,"aqi, air quality index, particulate matter",review
2,8,Health and economic effects of air pollution i...,PMC12538240,True,india,"ambient air pollution, air pollution",review
3,8,Respiratory deposition of particulate matter i...,PMC12663435,True,"india, delhi","particulate matter, air pollution",review
4,8,Impact of Housing Conditions and Air Quality A...,PMC12815361,True,india,"pm2.5, particulate matter, air pollution",review
5,8,Real-time impacts of air pollution on the heal...,PMC13289869,True,"india, delhi","pm2.5, particulate matter, air pollution",review
7,6,Ensemble stacking of machine learning models f...,PMC11883379,True,"india, hyderabad","aqi, air quality index, air pollution",review
8,6,Estimating health and economic burden of PM&lt...,PMC12287331,True,india,"particulate matter, air pollution",review
9,6,Efficient multi-station air quality prediction...,PMC12364328,True,delhi,"pm2.5, particulate matter",review
10,6,Effect of Ambient Air Pollutants on Acute chan...,PMC12572900,True,india,"aqi, air quality index, pm2.5, pm10, particula...",review
11,6,Alterations in neuroinflammatory and neurodege...,PMC12753801,True,"india, indian","ambient air pollution, air pollution, ozone",review
12,6,Role of wind in alteration of hilltop airborne...,PMC12838236,True,india,particulate matter,review
13,6,Role of medicines dispensation data in city-ba...,PMC12851262,True,"india, indian, pune","particulate matter, air pollution",review
14,6,A cross-sectional study on the respiratory hea...,PMC12995173,True,"india, tamil nadu","pm2.5, pm10",review
15,6,Systematic exposure bias in city-level air qua...,PMC13199542,True,"india, indian","aqi, air quality index, particulate matter",review
16,6,Cost-effective and scalable urban air quality ...,PMC13219415,True,india,"pm2.5, pm10, air pollution",review
17,6,Characterizing the Compound Extreme Temperatur...,PMC13282691,True,india,air pollution,review

In [ ]:
result["row_count"]

50

In [ ]:
result["high_score_count"]

18

In [ ]:
result["xml_count"]

47

In [ ]:
len(high_xml)

17

In [ ]:
# Optional: filter by a term in title or abstract
TERM = "Delhi"
mask = df["title"].str.contains(TERM, case=False, na=False) | df[
    "abstract_snippet"
].str.contains(TERM, case=False, na=False)
display(df.loc[mask, display_cols])

,score,title,pmcid,has_xml,location_terms,pollutant_terms,review_status
3,8,Respiratory deposition of particulate matter i...,PMC12663435,True,"india, delhi","particulate matter, air pollution",review
5,8,Real-time impacts of air pollution on the heal...,PMC13289869,True,"india, delhi","pm2.5, particulate matter, air pollution",review
9,6,Efficient multi-station air quality prediction...,PMC12364328,True,delhi,"pm2.5, particulate matter",review

## 5. Download review artifacts

Download the CSV or JSON to edit `review_status` (`include`, `review`, `exclude`) offline.

In [ ]:
from google.colab import files
import shutil

csv_path = result["review_paths"]["csv"]
files.download(csv_path)

# Optional: zip the entire query directory
zip_base = shutil.make_archive(str(OUTPUT_DIR), "zip", root_dir=OUTPUT_DIR.parent, base_dir=OUTPUT_DIR.name)
files.download(zip_base)

## 6. Iterative query refinement

Use this checklist after each run:

- **Too broad?** Add location or topic terms (e.g. `AND Delhi`)
- **Too narrow?** Remove restrictive terms or broaden synonyms
- **Missing fulltext?** Papers without PMCID cannot download XML; note `has_xml = false` rows

To refine: copy parameters into section 2, set `REVISION_OF` to the previous `QUERY_NAME`, and re-run sections 3–5.

In [ ]:
# Example: refined query (edit QUERY_NAME and QUERY_STRING in section 2, then re-run)
REFINED_QUERY_NAME = "aqi_india_delhi"
REFINED_QUERY_STRING = (
    '("air quality index" OR AQI OR PM2.5) AND India AND Delhi'
)
print("Set in section 2:")
print(f"  QUERY_NAME = {REFINED_QUERY_NAME!r}")
print(f"  QUERY_STRING = {REFINED_QUERY_STRING!r}")
print(f"  REVISION_OF = {QUERY_NAME!r}")

Set in section 2:
  QUERY_NAME = 'aqi_india_delhi'
  QUERY_STRING = '("air quality index" OR AQI OR PM2.5) AND India AND Delhi'
  REVISION_OF = 'aqi_india_pilot'

In [ ]:
# Compare two runs by pmcid/pmid (run after a refined query)
import json

def load_ids(path):
    with open(path, "r", encoding="utf-8") as handle:
        rows = json.load(handle)
    ids = set()
    for row in rows:
        key = row.get("pmcid") or row.get("pmid") or row.get("paper_id")
        if key:
            ids.add(key)
    return ids

prior_json = Path("/content/queries", QUERY_NAME if REVISION_OF is None else REVISION_OF, "review", "review_table.json")
current_json = Path(result["review_paths"]["json"])

if prior_json.is_file() and current_json.is_file():
    prior_ids = load_ids(prior_json)
    current_ids = load_ids(current_json)
    overlap = prior_ids & current_ids
    print(f"Prior run: {len(prior_ids)} papers")
    print(f"Current run: {len(current_ids)} papers")
    print(f"Overlap: {len(overlap)} papers")
    print(f"New in current run: {len(current_ids - prior_ids)}")
    print(f"Dropped from prior run: {len(prior_ids - current_ids)}")
else:
    print("Run a refined query first, or adjust prior_json path.")

Prior run: 50 papers
Current run: 50 papers
Overlap: 50 papers
New in current run: 0
Dropped from prior run: 0

## 7. Optional: persist to Google Drive

Colab sessions are ephemeral. Mount Drive and set `OUTPUT_DIR` under your Drive folder to keep results between sessions.

In [ ]:
from google.colab import drive

drive.mount("/content/drive")

# Example: OUTPUT_DIR = Path("/content/drive/MyDrive/semantic_corpus/queries", QUERY_NAME)

## 8. Next steps (outside this notebook)

1. Edit `review_status` in the downloaded CSV or JSON (`include` / `exclude`)
2. Ingest selected papers into a BAGIT corpus locally
3. Export a chatbot manifest for RAG indexing

See the [chatbot export contract](https://github.com/semanticClimate/semantic_corpus/blob/main/docs/chatbot_export_contract.md).